[tools]
dagger = "latest"
go = "latest"
node = "latest"
poetry = "latest"
python = "latest"
rust = "latest"
usage = "latest"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
