# nGet editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$fill\
$rust\
$lua\
$nodejs \
$golang\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$aws \
$time\
$line_break\
$character"""


# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✗](bold red)'

[directory]
style = 'blue'
read_only = ' 󰌾'
read_only_style = 'blue'
truncation_length = 7 
truncate_to_repo = true
home_symbol = '~'

[nodejs]
format = '[\[ $symbol ($version) \]]($style)'
symbol = ' '

[golang]
format = '[\[ $symbol($version) \] ]($style)'
symbol = ' '

[rust]
format = '[\[ $symbol($version) \] ]($style)'
symbol = ' '
style = 'red'

[lua]
format = '[\[ $symbol($version) \] ]($style)'
symbol = " "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = '[\[ $symbol$branch(:$remote_branch) \]]($style) '
symbol = " "

[git_status]
format = '([\[ $all_status$ahead_behind \]]($style) )'
style = 'bold purple'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[aws]
format = '[\[ aws $symbol ($profile)(\($region\)) \]]($style)'
symbol = " "

[time]
disabled = false
format = '[\[   $time \]]($style)'
time_format = '%Y-%m-%d %H:%M:%S'
time_range = '10:00:00-14:00:00'
style = 'bold blue'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

palette = 'catppuccin_mocha'
