[tools]
"github:clangd/clangd" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:pyright" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:black" = "latest"
"pipx:isort" = "latest"
ansible = "latest"
awscli = { version = "latest", symlink_bins = "true" }
buf = "latest"
bun = "latest"
circleci = "latest"
dagger = "latest"
databricks-cli = "latest"
go = "latest"
jq = "latest"
lua = "latest"
lua-language-server = "latest"
node = "latest"
pipx = "latest"
poetry = "latest"
prettier = "latest"
python = "latest"
rust = "latest"
rust-analyzer = "latest"
stylua = "latest"
syft = "latest"
taplo = "latest"
terraform = "latest"
terraform-ls = "latest"
trivy = "latest"
usage = "latest"
uv = "latest"
yamlfmt = "latest"
yarn = "latest"
yq = "latest"

[settings]
idiomatic_version_file_enable_tools = [
    "go",
    "node",
    "python",
    "terraform",
    "yarn",
]
lockfile = true
experimental = true

[tasks."install-euporie"]
description = "Install TUI Jupyter notebook editor and runner"
run = ["uv tool install euporie"]
