[tools]
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
ansible = "latest"
awscli = { version = "latest", symlink_bins = "true" }
bun = "latest"
circleci = "latest"
dagger = "latest"
databricks-cli = "latest"
go = "latest"
lua = "latest"
node = "latest"
pipx = "latest"
poetry = "latest"
python = "latest"
rust = "latest"
syft = "latest"
terraform = "latest"
trivy = "latest"
usage = "latest"
uv = "latest"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = [
    "go",
    "node",
    "python",
    "terraform",
    "yarn",
]
lockfile = true
experimental = true

[tasks."install-euporie"]
description = "Install TUI Jupyter notebook editor and runner"
run = ["uv tool install euporie"]
